platform :ios, "8.0"
use_frameworks!

pod 'Moya'
pod 'SwiftyJSON', '~> 2.2.1'

def testing_pods
    pod 'Quick', '~> 0.3.0'
    pod 'Nimble', '~> 1.0.0'
end

target 'API_MoyaTests' do
    testing_pods
end
